import { AccountId, ModifiedFileDimension } from '@postybirb/types';
import { EntityId, IEntity } from '../database/entity.interface';
import { IFileBuffer } from '../file/file-buffer.interface';
import { IFileDimensions } from '../file/file-dimensions.interface';
import { FileSubmissionMetadata } from './file-submission/file-submission-metadata.type';
import { ISubmission } from './submission.interface';

export type SubmissionFileId = EntityId;

/**
 * Represents a file attached to a submission for posting.
 *
 * @interface ISubmissionFile
 * @extends {IFileDimensions}
 * @extends {IEntity}
 */
export interface ISubmissionFile extends IFileDimensions, IEntity {
  /**
   * Parent submission.
   *
   * @type {ISubmission<FileSubmissionMetadata>}
   */
  submission: ISubmission<FileSubmissionMetadata>;

  submissionId: EntityId;

  /**
   * Name of the file.
   *
   * @type {string}
   */
  fileName: string;

  /**
   * Hash of the file.
   *
   * @type {string}
   */
  hash: string;

  /**
   * Mime Type of the file.
   *
   * @type {string}
   */
  mimeType: string;

  /**
   * Reference to the buffer entity.
   *
   * @type {IFileBuffer}
   */
  file: IFileBuffer;

  /**
   * Optional thumbnail for the file.
   * Should be autogenerated if possible.
   *
   * @type {(IFileBuffer | undefined)}
   */
  thumbnail?: IFileBuffer;

  /**
   * Alternate file to post instead of the main.
   * Primarily used for Text based submission.
   *
   * @type {(IFileBuffer | undefined)}
   */
  altFile?: IFileBuffer;

  /**
   * Status flag for internal processing.
   *
   * @type {boolean}
   */
  hasThumbnail: boolean;

  /**
   * Status flag for internal processing.
   *
   * @type {boolean}
   */
  hasAltFile: boolean;

  /**
   * Whether or not the file has a custom thumbnail that was not
   * auto-generated and instead added by the user.
   * @type {boolean}
   */
  hasCustomThumbnail: boolean;

  primaryFileId: EntityId;

  thumbnailId?: EntityId;

  altFileId?: EntityId;

  metadata: SubmissionFileMetadata;

  order: number;
}

export interface SubmissionFileMetadata {
  /**
   * The alternative text for the file.
   * @type {string}
   */
  altText?: string;

  /**
   * The spoiler text for the file.
   * @type {string}
   */
  spoilerText?: string;

  /**
   * The dimensions of the file for different websites.
   * @type {Record<AccountId, ModifiedFileDimension>}
   */
  dimensions: Record<AccountId, ModifiedFileDimension>;

  /**
   * The list of websites where the file is ignored.
   * @type {AccountId[]}
   */
  ignoredWebsites: AccountId[];

  /**
   * The source URLs for the file.
   * @type {string[]}
   */
  sourceUrls: string[];
}

export const DefaultSubmissionFileMetadata: () => SubmissionFileMetadata =
  () => ({
    altText: '',
    spoilerText: '',
    dimensions: {},
    ignoredWebsites: [],
    sourceUrls: [],
  });
