import { EntityId, IEntity } from '../database/entity.interface';
import { IFileBuffer } from '../file/file-buffer.interface';
import { IFileDimensions } from '../file/file-dimensions.interface';
import { FileSubmissionMetadata } from './file-submission/file-submission-metadata.type';
import { ISubmission } from './submission.interface';

export type SubmissionFileId = EntityId;

/**
 * Represents a file attached to a submission for posting.
 *
 * @interface ISubmissionFile
 * @extends {IFileDimensions}
 * @extends {IEntity}
 */
export interface ISubmissionFile extends IFileDimensions, IEntity {
  /**
   * Parent submission.
   *
   * @type {ISubmission<FileSubmissionMetadata>}
   */
  submission: ISubmission<FileSubmissionMetadata>;

  /**
   * Name of the file.
   *
   * @type {string}
   */
  fileName: string;

  /**
   * Hash of the file.
   *
   * @type {string}
   */
  hash: string;

  /**
   * Mime Type of the file.
   *
   * @type {string}
   */
  mimeType: string;

  /**
   * Reference to the buffer entity.
   *
   * @type {IFileBuffer}
   */
  file: IFileBuffer;

  /**
   * Optional thumbnail for the file.
   * Should be autogenerated if possible.
   *
   * @type {(IFileBuffer | undefined)}
   */
  thumbnail?: IFileBuffer;

  /**
   * Alternate file to post instead of the main.
   * Primarily used for Text based submission.
   *
   * @type {(IFileBuffer | undefined)}
   */
  altFile?: IFileBuffer;

  /**
   * Status flag for internal processing.
   *
   * @type {boolean}
   */
  hasThumbnail: boolean;

  /**
   * Status flag for internal processing.
   *
   * @type {boolean}
   */
  hasAltFile: boolean;

  /**
   * Whether or not the file has a custom thumbnail that was not
   * auto-generated and instead added by the user.
   * @type {boolean}
   */
  hasCustomThumbnail: boolean;

  primaryFileId: EntityId;

  thumbnailId?: EntityId;

  altFileId?: EntityId;
}
