export enum UnitOfWorkState {
  NEW = 'NEW',
  PENDING = 'PENDING',
  EXECUTING = 'EXECUTING',
  VALIDATING = 'VALIDATING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  RATE_LIMITED = 'RATE_LIMITED',
}