nodeLinker: node-modules
logFilters:
  # Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
  - code: YN0086
    level: discard

supportedArchitectures:
  cpu: ['current', 'x64', 'arm64']
