logFilters:
  # NX packages peer dependencies make a lot of warnings that does not affect code in any way
  - code: YN0086
    level: discard

  # This warning doesn't make sense. This package is not referenced in code at all and wasn't updated in 2 years
  - code: YN0002
    level: discard
    text: doesn't provide @mantine/utils (p2df71b), requested by @blocknote/mantine.

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
