name: Build/Release

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS (x64)
            os: macos-latest
            platform: mac
            arch: x64
          - name: macOS (arm64)
            os: macos-latest
            platform: mac
            arch: arm64
          - name: Linux (x64)
            os: ubuntu-latest
            platform: linux
            arch: x64
          - name: Linux (arm64)
            os: ubuntu-24.04-arm
            platform: linux
            arch: arm64
          - name: Windows (x64)
            os: windows-latest
            platform: win
            arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # This must be run after node setup but before any yarn commands
      - name: Enable corepack to use Yarn v4
        run: |
          corepack enable
          corepack prepare --activate

      # Cache Electron binaries (include arch to avoid cross-arch cache pollution)
      - name: Cache Electron binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            node_modules/.cache/electron
          key: ${{ runner.os }}-${{ matrix.arch }}-electron-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-electron-cache-

      # Install dependencies with proper caching
      - name: Install dependencies
        run: yarn install --immutable
        env:
          CYPRESS_INSTALL_BINARY: 0
          ELECTRON_CACHE: ~/.cache/electron
          ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder

      # Linux tooling (snapcraft for snap target)
      - name: Install snapcraft
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install snapcraft --classic

      # ✅ Fix for Linux arm64: electron-builder’s bundled fpm is x86, so install system fpm on ARM
      - name: Install Ruby + fpm (system) for Linux arm64 packaging
        if: matrix.platform == 'linux' && matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential rpm
          sudo gem install --no-document fpm
          echo "Ruby:"; ruby -v
          echo "fpm:"; fpm --version

      - name: Inject Application Insights connection string
        env:
          APP_INSIGHTS_KEY: ${{ secrets.APP_INSIGHTS_KEY }}
        run: yarn inject:app-insights

      # Build the application
      - name: Build application
        run: yarn build:prod
        env:
          NODE_ENV: production

      # Build Electron app
      - name: Build Electron app
        run: yarn electron-builder --${{ matrix.platform }} --${{ matrix.arch }} --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_IDENTITY_AUTO_DISCOVERY: true
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAPCRAFT_BUILD_ENVIRONMENT: host
          # ✅ Forces electron-builder to use the system fpm you installed above (critical on ARM)
          USE_SYSTEM_FPM: true
