// Constant variables
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const WEBSITE_IMPLEMENTATIONS = 'WEBSITE_IMPLEMENTATIONS';

// Database Repository Constants
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const WEBSITE_DATA_REPOSITORY = 'WEBSITE_DATA_REPOSITORY';
export const FILE_REPOSITORY = 'FILE_REPOSITORY';
export const FILE_DATA_REPOSITORY = 'FILE_DATA_REPOSITORY';
