import { SelectOption } from '@postybirb/form-builder';

export const FurAffinityThemes: SelectOption[] = [
  {
    label: 'General Things',
    items: [
      { value: '1', label: 'All' },
      { value: '2', label: 'Abstract' },
      { value: '3', label: 'Animal related (non-anthro)' },
      { value: '4', label: 'Anime' },
      { value: '5', label: 'Comics' },
      { value: '6', label: 'Doodle' },
      { value: '7', label: 'Fanart' },
      { value: '8', label: 'Fantasy' },
      { value: '9', label: 'Human' },
      { value: '10', label: 'Portraits' },
      { value: '11', label: 'Scenery' },
      { value: '12', label: 'Still Life' },
      { value: '13', label: 'Tutorials' },
      { value: '14', label: 'Miscellaneous' },
    ],
  },
  {
    label: 'Specialty',
    items: [
      { value: '101', label: 'Baby fur' },
      { value: '102', label: 'Bondage' },
      { value: '103', label: 'Digimon' },
      { value: '104', label: 'Fat Furs' },
      { value: '105', label: 'Fetish Other' },
      { value: '106', label: 'Fursuit' },
      { value: '119', label: 'Gore / Macabre Art' },
      { value: '107', label: 'Hyper' },
      { value: '121', label: 'Hypnosis' },
      { value: '108', label: 'Inflation' },
      { value: '109', label: 'Macro / Micro' },
      { value: '110', label: 'Muscle' },
      { value: '111', label: 'My Little Pony / Brony' },
      { value: '112', label: 'Paw' },
      { value: '113', label: 'Pokemon' },
      { value: '114', label: 'Pregnancy' },
      { value: '115', label: 'Sonic' },
      { value: '116', label: 'Transformation' },
      { value: '120', label: 'TF / TG' },
      { value: '117', label: 'Vore' },
      { value: '118', label: 'Water Sports' },
      { value: '100', label: 'General Furry Art' },
    ],
  },
  {
    label: 'Music',
    items: [
      { value: '201', label: 'Techno' },
      { value: '202', label: 'Trance' },
      { value: '203', label: 'House' },
      { value: '204', label: '90s' },
      { value: '205', label: '80s' },
      { value: '206', label: '70s' },
      { value: '207', label: '60s' },
      { value: '208', label: 'Pre-60s' },
      { value: '209', label: 'Classical' },
      { value: '210', label: 'Game Music' },
      { value: '211', label: 'Rock' },
      { value: '212', label: 'Pop' },
      { value: '213', label: 'Rap' },
      { value: '214', label: 'Industrial' },
      { value: '200', label: 'Other Music' },
    ],
  },
];
