import { getMimeTypeForFile } from './mime-helper';

const SUPPORTED_MIME: string[] = [
  'text/cache-manifest',
  'text/calendar',
  'text/coffeescript',
  'text/css',
  'text/csv',
  'text/html',
  'text/jade',
  'text/javascript',
  'text/ecmascript',
  'text/javascript1.0',
  'text/javascript1.1',
  'text/javascript1.2',
  'text/javascript1.3',
  'text/javascript1.4',
  'text/javascript1.5',
  'text/jscript',
  'text/jsx',
  'text/less',
  'text/livescript',
  'text/x-ecmascript',
  'text/x-javascript',
  'text/json',
  'text/markdown',
  'text/x-markdown',
  'text/mathml',
  'text/x.gcode',
  'text/x-gcode',
  'text/n3',
  'text/plain',
  'text/prs.lines.tag',
  'text/richtext',
  'text/rtf',
  'text/sgml',
  'text/stylus',
  'text/tab-separated-values',
  'text/troff',
  'text/turtle',
  'text/uri-list',
  'text/vcard',
  'text/vnd.curl',
  'text/vnd.curl.dcurl',
  'text/vnd.curl.mcurl',
  'text/vnd.curl.scurl',
  'text/vnd.fly',
  'text/vnd.fmi.flexstor',
  'text/vnd.graphviz',
  'text/vnd.in3d.3dml',
  'text/vnd.in3d.spot',
  'text/vnd.sun.j2me.app-descriptor',
  'text/vnd.wap.si',
  'text/vnd.wap.sl',
  'text/vnd.wap.wml',
  'text/vnd.wap.wmlscript',
  'text/vtt',
  'text/x-asm',
  'text/x-c',
  'text/x-component',
  'text/x-fortran',
  'text/x-handlebars-template',
  'text/x-java-source',
  'text/x-java',
  'text/x-lua',
  'text/x-nfo',
  'text/x-opml',
  'text/x-pascal',
  'text/x-processing',
  'text/x-python',
  'text/x-sass',
  'text/x-scss',
  'text/x-setext',
  'text/x-typescript',
  'text/x-uuencode',
  'text/x-vcalendar',
  'text/x-vcard',
  'text/xml',
  'text/yaml',
  'application/json',
  'application/ld+json',
  'application/msword',
  'application/pdf',
  'application/rtf',
  'application/vnd.ms-excel',
  'application/vnd.ms-powerpoint',
  'application/vnd.oasis.opendocument.text',
  'application/vnd.oasis.opendocument.spreadsheet',
  'application/vnd.oasis.opendocument.presentation',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/x-httpd-php',
  'application/x-sh',
  'application/x-yaml',
  'application/xml',
];

export function supportsText(mimeType: string): boolean {
  return SUPPORTED_MIME.includes(mimeType);
}

export function isText(filenameOrExtension: string): boolean {
  const mimeType = getMimeTypeForFile(filenameOrExtension);
  return (
    SUPPORTED_MIME.includes(mimeType ?? '') || supportsText(filenameOrExtension)
  );
}
