import { SelectOption } from '@postybirb/form-builder';

const rawSoftware = [
  '3D Coat',
  '3D Slash',
  '3DVIA Shape',
  'Ableton Live',
  'AC3D',
  'Acorn',
  'Adobe After Effects',
  'Adobe Animate',
  'Adobe Audition',
  'Adobe Dreamweaver',
  'Adobe Flash',
  'Adobe Flash Builder',
  'Adobe Fuse',
  'Adobe Illustrator',
  'Adobe Indesign',
  'Adobe Lightroom',
  'Adobe Muse',
  'Adobe Photoshop',
  'Adobe Premiere Pro',
  'Adobe Project Felix',
  'Adobe Spark',
  'Adobe SpeedGrade',
  'Adobe Story Plus',
  'Affinity Designer',
  'Affinity Photo',
  'Anim8or',
  'Animation:Master',
  'Anime Studio',
  'ArchiCAD',
  'ArtRage',
  'Aseprite',
  'AutoCAD',
  'Autodesk 123D',
  'Autodesk 3ds Max',
  'Autodesk Inventor',
  'Autodesk Maya',
  'Autodesk Mudbox',
  'Autodesk Revit',
  'Autodesk Sketchbook Pro',
  'Autodesk Softimage',
  'AutoQ3D',
  'Bitwig Studio',
  'Blender',
  'BricsCAD',
  'BRL-CAD',
  'Bryce',
  'Cakewalk Sonar',
  'Carrara',
  'CATIA',
  'Cheetah3D',
  'CINEMA 4D',
  'CinePaint',
  'CityEngine',
  'Clara.io',
  'Clip Studio Paint',
  'Cockos Reaper',
  'Comic Studio',
  'Corel Painter',
  'Cubase',
  'Daz 3D',
  'DesignSpark Mechanical',
  'Electric Image Animation System',
  'Exa Corporation',
  'Firealpaca',
  'FL Studio',
  'Flux',
  'Form-Z',
  'fragMOTION',
  'FreeCAD',
  'GameMaker Studio 2',
  'GarageBand',
  'Geomodeller3D',
  'Gimp',
  'HDR Light Studio (lighting softw',
  'Hexagon',
  'Houdini',
  'IRONCAD',
  'K-3D',
  'Krita',
  'LightWave 3D',
  'Logic Pro',
  'Magix Acid',
  'Magix Fastcut',
  'Magix Movie Edit Pro',
  'Magix Music Studio',
  'Magix Samplitude',
  'Magix Sequoia',
  'Magix SOUND FORGE',
  'Magix Vegas',
  'Magix Video easy',
  'Magix Xara Page & Layout Designe',
  'Magix Xara Photo & Graphic Desig',
  'Makers Empire 3D',
  'Manga Studio',
  'MASSIVE',
  'MATLAB',
  'MechDesigner',
  'MediBang Paint',
  'Metasequoia',
  'MikuMikuDance',
  'Milkshape 3D',
  'Mischief',
  'Modo',
  'Moi3D',
  'MyPaint',
  'None',
  'Nuendo',
  'Onshape',
  'Open Canvas',
  'Open CASCADE',
  'OpenSCAD',
  'Other',
  'Paint 3D',
  'Paint Tool SAI',
  'PaintShop Pro',
  'Paintstorm Studio',
  'PhotoPlus',
  'Photoscape',
  'Pinta',
  'Pixelmator',
  'Poser',
  'Pro Tools',
  'Pro/ENGINEER',
  'Procreate',
  'Propellerhead Reason',
  'Quake Army Knife',
  'RaySupreme',
  'Realsoft 3D',
  'Remo 3D',
  'Renoise',
  'RFEM',
  'Rhinoceros 3D',
  'ROBLOX Studio',
  'Sculptris',
  'Seamless3d',
  'Seashore',
  'Shade 3D',
  'Silo',
  'Sketchbook Pro',
  'Sketchup',
  'Solid Edge',
  'solidThinking',
  'SolidWorks',
  'Source Filmmaker',
  'SpaceClaim',
  'Strata 3D',
  'Studio One',
  'Sweet Home 3D',
  'Swift 3D',
  'Tayasui Sketches Pro',
  'Tekla Structures',
  'Toon Boom Harmony',
  'Tracktion',
  'TrueSpace',
  'Unigraphics',
  'Unity',
  'Unreal Engine 4',
  'Vectorworks',
  'Wings 3D',
  'Wolfram Mathematica',
  'ZBrush',
  'Zmodeler',
  'ZW3D',
  'ZWCAD',
];

export const PicartoSoftware: SelectOption[] = rawSoftware.map((v) => ({
  label: v,
  value: v,
}));
