import { SelectOption } from '@postybirb/form-builder';

const rawCategories = [
  'Creative',
  'Character Design',
  'Concept Art',
  'Animation',
  'Abstract Drawing',
  'Anime',
  'Manga',
  'Furry',
  'Music',
  'Comic',
  'Coding',
  'Creative Writing',
  'Game Development',
  'Sculpture',
  'Traditional Art',
  'Pony',
  'Cartoon',
  '3D Modeling',
  '3D VFX',
  'Realistic',
  'Rendering',
  'Adult',
  'Hentai',
  'Illustration',
  'Pixel Art',
  'Caricature',
  'Crafting',
  'Cosplay',
  'Food & Cooking',
  'Watercolor',
  'Painting',
  'Drawing',
  'Design',
  'Perler',
  'Glass Work',
  'Jewelry',
  'Chainmaille',
  'Figurines',
  'Crossstitch',
  'Vector',
  'Voiceacting',
  'Papercraft',
  'Robotics',
  'Leatherwork',
  'Sewing',
  'Dancing',
  'Woodworking',
  'Magic',
  'Architecture',
  'Clothes design',
  'Storyboarding',
  'Nature & Landscape',
  'Video Editing',
  'Gaming',
  'Education',
  'IRL',
  'Always ON',
  'ASMR',
  'Podcast',
  'Talkshow',
];

export const PicartoCategories: SelectOption[] = rawCategories.map((v) => ({
  label: v,
  value: v,
}));
